### ISSUE TITLE
초보입니다. 프로그램 실행이 안되어요..

### ISSUE THREAD

**Issue by KIMYOON11** [gilbutITbook/080298#1]
종목을 조회하고 나서 아래와 같은 메시지가 뜨면서 실행이 안되네요.. 코드는 보고 그대로 따라한 것이라 틀린 것이 없는 것으로 확인 하였습니다. 뭐가 문제일까요?? ㅠㅠㅠㅠㅠ

Traceback (most recent call last):
  File "C:\Users\??\PycharmProjects\SystemTrading\strategy\RSIStrategy.py", line 37, in init_strategy
    self.kiwoom.get_order()
  File "C:\Users\??\PycharmProjects\SystemTrading\api\Kiwoom.py", line 291, in get_order
    return self.tr_data
AttributeError: 'Kiwoom' object has no attribute 'tr_data'

**Comment by KIMYOON11** [comment]
.

**Comment by gilbutITbook** [comment]
안녕하세요. 저자님께서 아래와 같이 답변을 주셨습니다. 

​kiwoom.py의 _on_receive_tr_data 함수 밑 elif rqname == "opt10075_req": 블록에 self.tr_data = self.order 코드가 있는지 확인 부탁드립니다.

추가 문의가 있으실 때는 '길벗출판사 홈페이지 → 고객센터 → 1:1 문의'에서 도서를 검색하신 후 문의를 남겨주시면 더 빠르게 답변을 받아보실 수 있습니다. 감사합니다.
